---
title: ''
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(readxl)

allrea <- read_excel("/Users/francopicone/Desktop/Data+/REA_ASR_3845_finalv2.xlsx")

allrea

```

```{r}
allrea$latitude <- jitter(allrea$latitude)
allrea$longitude <- jitter(allrea$longitude)
allrea$system <- formatC(allrea$system, width=5, format="d", flag="0")

cleantable <- allrea %>%
  select(
    County = county,
    City = city,
    State = state,
    Zipcode = zip,
    System = system,
    Year = year,
    MilesEnergized = op_me,
    CustomersPerMile = op_cpm,
    RevenuePerMile = op_rpm,
    kWhPerResidentialCustomer = kwh_per_cc1,
    LogkWhPerResidentialCustomer = ln_kwh1,
    Lat = latitude,
    Long = longitude
  )
```


```{r}
## Make dataset shiny compatible
library(leaflet)
library(RColorBrewer)
library(scales)
library(lattice)
library(dplyr)

# Leaflet bindings are a bit slow; for now we'll just sample to compensate
readata <- allrea
# By ordering by centile, we ensure that the (comparatively rare) SuperZIPs
# will be drawn last and thus be easier to see
readata <- readata[order(readata$prop_score),]

function(input, output, session) {

  ## Interactive Map ###########################################

  # Create the map
  output$map <- renderLeaflet({
    leaflet() %>%
      addTiles(
        urlTemplate = "//{s}.tiles.mapbox.com/v3/jcheng.map-5ebohr46/{z}/{x}/{y}.png",
        attribution = 'Maps by <a href="http://www.mapbox.com/">Mapbox</a>'
      ) %>%
      setView(lng = -93.85, lat = 37.45, zoom = 4)
  })

  # A reactive expression that returns the set of zips that are
  # in bounds right now
  systemInBounds <- reactive({
    if (is.null(input$map_bounds))
      return(readata[FALSE,])
    bounds <- input$map_bounds
    latRng <- range(bounds$north, bounds$south)
    lngRng <- range(bounds$east, bounds$west)

    subset(readata,
      latitude >= latRng[1] & latitude <= latRng[2] &
        longitude >= lngRng[1] & longitude <= lngRng[2])
  })

  # Precalculate the breaks we'll need for the two histograms
  psBreaks <- hist(plot = FALSE, allrea$prop_score, breaks = 20)$breaks

  output$histps <- renderPlot({
    # If no zipcodes are in view, don't plot
    if (nrow(systemInBounds()) == 0)
      return(NULL)

    hist(systemInBounds()$prop_score,
      breaks = psBreaks,
      main = "Propensity score (visible zips)",
      xlab = "Propensity Score",
      xlim = range(allrea$prop_score),
      col = '#00DD00',
      border = 'white')
  })
## WHAT KIND OF PLOT DO WE WANT
#  output$scatterCollegeIncome <- renderPlot({
#    # If no zipcodes are in view, don't plot
#    if (nrow(zipsInBounds()) == 0)
#      return(NULL)
#
#    print(xyplot(income ~ college, data = zipsInBounds(), xlim = range(allzips$college), ylim = #range(allzips$income)))
#  })

  # This observer is responsible for maintaining the circles and legend,
  # according to the variables the user has chosen to map to color and size.
  observe({
    colorBy <- input$color
    sizeBy <- input$size
    
## Special coloring cases 
    if (colorBy == "Treatment") {
      # Color and palette are treated specially in the "superzip" case, because
      # the values are categorical instead of continuous.
      colorData <- ifelse(readata$treated == 1, "yes", "no")
      pal <- colorFactor("viridis", colorData)
    } else {
      colorData <- readata[[colorBy]]
      pal <- colorBin("viridis", colorData, 7, pretty = FALSE)
    }
    
## SPecial Sizing cases
#    if (sizeBy == "superzip") {
#      # Radius is treated specially in the "superzip" case.
#      radius <- ifelse(zipdata$centile >= (100 - input$threshold), 30000, 3000)
#    } else {
#      radius <- zipdata[[sizeBy]] / max(zipdata[[sizeBy]]) * 30000
#   }

    leafletProxy("map", data = readata) %>%
      clearShapes() %>%
      addCircles(~longitude, ~latitude, radius=radius, layerId=~system,
        stroke=FALSE, fillOpacity=0.4, fillColor=pal(colorData)) %>%
      addLegend("bottomleft", pal=pal, values=colorData, title=colorBy,
        layerId="colorLegend")
  })
  
# CODE FOR POPUP -- TRI Modify this
  # Show a popup at the given location
  showSitePopup <- function(system, lat, lng) {
    selectedSite <- allrea[allrea$system == system,]
    content <- as.character(tagList(
      tags$h4("Score:", as.integer(selectedSite$prop_score)),
      tags$strong(HTML(sprintf("%s, %s %s",
        selectedSite$city.x, selectedSite$state.x, selectedSite$system
      ))), tags$br(),
      sprintf("kWh Consumed Per Customer: %s", selectedSite$kwh_per_cc1), tags$br(),
      sprintf("Miles Energized: %s%", selectedSite$op_me), tags$br(),
      sprintf("Customers Per Mile: %s%", selectedSite$op_cpm), tags$br(),
      sprintf("Revenue Per Mile: %s%", selectedSite$op_rpm), tags$br(),
      sprintf("Number of Farms: %s%", selectedSite$farms), tags$br(),
      sprintf("Farm Population: %s%", selectedSite$farm_pop), tags$br(),
      sprintf("Percent Farmland: %s%", selectedSite$plf)
    ))
    leafletProxy("map") %>% addPopups(lng, lat, content, layerId = system)
  }

  # When map is clicked, show a popup with city info
  observe({
    leafletProxy("map") %>% clearPopups()
    event <- input$map_shape_click
    if (is.null(event))
      return()

    isolate({
      showSitePopup(event$id, event$lat, event$lng)
    })
  })

## ADDITIONAL TAB --ZHIHAO Reference this 
  ## Data Explorer ###########################################

  observe({
    cities <- if (is.null(input$states)) character(0) else {
      filter(cleantable, State %in% input$states) %>%
        `$`('City') %>%
        unique() %>%
        sort()
    }
    stillSelected <- isolate(input$cities[input$cities %in% cities])
    updateSelectizeInput(session, "cities", choices = cities,
      selected = stillSelected, server = TRUE)
  })

  observe({
    systems <- if (is.null(input$states)) character(0) else {
      cleantable %>%
        filter(State %in% input$states,
          is.null(input$cities) | City %in% input$cities) %>%
        `$`('System') %>%
        unique() %>%
        sort()
    }
    stillSelected <- isolate(input$systems[input$systems %in% systems])
    updateSelectizeInput(session, "systems", choices = systems,
      selected = stillSelected, server = TRUE)
  })

  observe({
    if (is.null(input$goto))
      return()
    isolate({
      map <- leafletProxy("map")
      map %>% clearPopups()
      dist <- 0.5
      system <- input$goto$system
      lat <- input$goto$lat
      lng <- input$goto$lng
      showSitePopup(system, lat, lng)
      map %>% fitBounds(lng - dist, lat - dist, lng + dist, lat + dist)
    })
  })

  output$systable <- DT::renderDataTable({
    df <- cleantable %>%
      filter(
        Score >= input$minScore,
        Score <= input$maxScore,
        is.null(input$states) | State %in% input$states,
        is.null(input$cities) | City %in% input$cities,
        is.null(input$systems) | Zipcode %in% input$systems
      ) %>%
      mutate(Action = paste('<a class="go-map" href="" data-lat="', Lat, '" data-long="', Long, '" data-system="', System, '"><i class="fa fa-crosshairs"></i></a>', sep=""))
    action <- DT::dataTableAjax(session, df, outputId = "systable")

    DT::datatable(df, options = list(ajax = list(url = action)), escape = FALSE)
  })
}
```

```{r}
## UI Setup

library(leaflet)

# Choices for drop-downs
vars <- c(
  "Treatment" = "treated",
  "Propensity Score" = "prop_score"
)


navbarPage("REA Stops and Sites", id="nav",

  tabPanel("Interactive map",
    div(class="outer",

      tags$head(
        # Include our custom CSS
        includeCSS("styles.css"),
        includeScript("gomap.js")
      ),

      # If not using custom CSS, set height of leafletOutput to a number instead of percent
      leafletOutput("map", width="100%", height="100%"),

      # Shiny versions prior to 0.11 should use class = "modal" instead.
      absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE,
        draggable = TRUE, top = 60, left = "auto", right = 20, bottom = "auto",
        width = 330, height = "auto",

        h2("REA explorer"),

        selectInput("color", "Color", vars),
        selectInput("size", "Size", vars, selected = "adultpop"),
#        conditionalPanel("input.color == 'superzip' || input.size == 'superzip'",
          # Only prompt for threshold when coloring or sizing by superzip
#          numericInput("threshold", "SuperZIP threshold (top n percentile)", 5)
#       ),

        plotOutput("histps", height = 200),
#        plotOutput("scatterCollegeIncome", height = 250)
        ),

      tags$div(id="cite",
        'Data compiled for ', tags$em('Coming Apart: The State of White America, 1960–2010'), '  by Charles Murray (Crown Forum, 2012).'
      )
    )
  ),

  tabPanel("Data explorer",
    fluidRow(
      column(3,
        selectInput("states", "States", c("All states"="", structure(state.abb, names=state.name), "Washington, DC"="DC"), multiple=TRUE)
      ),
      column(3,
        conditionalPanel("input.states",
          selectInput("cities", "Cities", c("All cities"=""), multiple=TRUE)
        )
      ),
      column(3,
        conditionalPanel("input.states",
          selectInput("systems", "Systems", c("All systems"=""), multiple=TRUE)
        )
      )
    ),
    fluidRow(
      column(1,
        numericInput("minScore", "Min score", min=0, max=100, value=0)
      ),
      column(1,
        numericInput("maxScore", "Max score", min=0, max=100, value=100)
      )
    ),
    hr(),
    DT::dataTableOutput("systable")
  ),

  conditionalPanel("false", icon("crosshair"))
)
```

```{r}
## This was code to add the "remaining apps" to the Rshiny gallery, so I'm not sure if we actually need this

##THIS IS A JAVASCRIPT CODE CHUNK WE NEED TO USE AS A WRAPPER

## When locator icon in datatable is clicked, go to that spot on the map
$(document).on("click", ".go-map", function(e) {
  e.preventDefault();
  $el = $(this);
  var lat = $el.data("lat");
  var long = $el.data("long");
  var zip = $el.data("zip");
  $($("#nav a")[0]).tab("show");
  Shiny.onInputChange("goto", {lat: lat,
    lng: long,
    zip: zip,
    nonce: Math.random()
    });
});
```

```{r}
## This was code to add the "remaining apps" to the Rshiny gallery, so I'm not sure if we actually need this

## This is also a CSS file being used as a wrapper
input[type="number"] {
  max-width: 80%;
}

div.outer {
  position: fixed;
  top: 41px;
  left: 0;
  right: 0;
  bottom: 0;
  overflow: hidden;
  padding: 0;
}

/* Customize fonts */
body, label, input, button, select { 
  font-family: 'Helvetica Neue', Helvetica;
  font-weight: 200;
}
h1, h2, h3, h4 { font-weight: 400; }

#controls {
  /* Appearance */
  background-color: white;
  padding: 0 20px 20px 20px;
  cursor: move;
  /* Fade out while not hovering */
  opacity: 0.65;
  zoom: 0.9;
  transition: opacity 500ms 1s;
}
#controls:hover {
  /* Fade in while hovering */
  opacity: 0.95;
  transition-delay: 0;
}

/* Position and style citation */
#cite {
  position: absolute;
  bottom: 10px;
  left: 10px;
  font-size: 12px;
}

/* If not using map tiles, show a white background */
.leaflet-container {
  background-color: white !important;
}
```
